В файле `HW01.ipynb` должны быть:

1. Импорт библиотеки NumPy с общепринятым сокращением.
2. Примеры создания массивов:
   - из обычных списков;
   - с использованием функций `zeros`, `ones`, `arange` или аналогичных.
3. Демонстрация атрибутов:
   - вывод формы (shape) и типа данных (dtype) для одного из массивов.
4. Примеры индексирования и срезов:
   - получение отдельного элемента;
   - извлечение подмассива с помощью среза.
5. Примеры векторных операций и базовых статистик:
   - поэлементное сложение или умножение массивов;
   - вычисление средней величины (`mean`) или другой простой статистики.

Желательно добавить несколько комментариев в коде, кратко поясняющих, что делает каждая операция.

---


In [1]:
import numpy as np

Массивы

In [3]:
#создадим одномерный массив
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
#создадим двумерный массив 
a2 = np.array([['a','b','c'], [1,2,3]])
a2

array([['a', 'b', 'c'],
       ['1', '2', '3']], dtype='<U21')

In [5]:
# двумерный массив из нулей, размером 4 на 4
b=np.zeros((4,4)) 
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
#одномерный массив из единиц в количестве 2
b2 = np.ones((2))
b2

array([1., 1.])

In [8]:
#создать массив с заданной последовательностью и шагом
c=np.arange(20, 30, 2)
c

array([20, 22, 24, 26, 28])

Демонстрация атрибутов:
вывод формы (shape) и типа данных (dtype) для одного из массивов.

In [16]:
#выведем форму и тип данных для созданного ранее массива a2
print(np.shape(a2))
print(type(a2))

(2, 3)
<class 'numpy.ndarray'>


Примеры индексирования и срезов:
получение отдельного элемента;
извлечение подмассива с помощью среза.

In [18]:
#элемент массива a2 [0,0] - первый элемент первой строки
a2[0,0]

np.str_('a')

In [19]:
#извлечение подмассива с помощью среза
#извлекаем из всех строк элементы с 0 по 2(не включая)
a2[:, 0:2]

array([['a', 'b'],
       ['1', '2']], dtype='<U21')

In [25]:
#извлекаем первый элемент первой строки
a2[0, 0]

np.str_('a')

Примеры векторных операций и базовых статистик:
поэлементное сложение или умножение массивов;
вычисление средней величины (mean) или другой простой статистики.

In [31]:
#создадим массивы с рандомными целыми числовыми значениями
z1 = np.random.randint(0, 100, 3)
z2 = np.random.randint(0, 100, 3)
print(z1)
print(z2)

[34 10 88]
[83 34 85]


In [32]:
#поэлементарное сложение
res = z1 + z2
res

array([117,  44, 173])

In [33]:
#умножение массивов
res2 = z1 * z2
res2

array([2822,  340, 7480])

In [36]:
#вычисление средней величины
print(np.mean(res2))

3547.3333333333335


In [ ]:
#